/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.4.0
 *
 * Project: 'uav.Debug+Control' 
 * Target:  'Debug+Control' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.3.0 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
