/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'uav.Debug+NUCLEO-F446RE' 
 * Target:  'Debug+NUCLEO-F446RE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.1.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.1.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.1.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.1.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_1@11.1.0 */
#define RTE_RTOS_FreeRTOS_HEAP_1        /* RTOS FreeRTOS Heap 1 */
/* ARM::RTOS&FreeRTOS:Timers@11.1.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* Keil::CMSIS Driver:I2C@3.0.0 */
#define RTE_Drivers_I2C1                /* Driver I2C1 */
#define RTE_Drivers_I2C2                /* Driver I2C2 */
#define RTE_Drivers_I2C3                /* Driver I2C3 */
#define RTE_Drivers_I2C4                /* Driver I2C4 */
#define RTE_Drivers_I2C5                /* Driver I2C5 */
#define RTE_Drivers_I2C6                /* Driver I2C6 */
#define RTE_Drivers_I2C7                /* Driver I2C7 */
#define RTE_Drivers_I2C8                /* Driver I2C8 */
/* Keil::CMSIS Driver:USART@3.0.0 */
#define RTE_CMSIS_Driver_USART1         /* Driver USART1  */
#define RTE_CMSIS_Driver_USART2         /* Driver USART2  */
#define RTE_CMSIS_Driver_USART3         /* Driver USART3  */
#define RTE_CMSIS_Driver_USART4         /* Driver USART4  */
#define RTE_CMSIS_Driver_USART5         /* Driver USART5  */
#define RTE_CMSIS_Driver_USART6         /* Driver USART6  */
#define RTE_CMSIS_Driver_USART7         /* Driver USART7  */
#define RTE_CMSIS_Driver_USART8         /* Driver USART8  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART10        /* Driver USART10 */
#define RTE_CMSIS_Driver_USART11        /* Driver USART11 */
#define RTE_CMSIS_Driver_USART12        /* Driver USART12 */
#define RTE_CMSIS_Driver_USART13        /* Driver USART13 */
#define RTE_CMSIS_Driver_USART14        /* Driver USART14 */
#define RTE_CMSIS_Driver_USART15        /* Driver USART15 */
#define RTE_CMSIS_Driver_USART21        /* Driver USART21 (LPUART1) */
#define RTE_CMSIS_Driver_USART22        /* Driver USART22 (LPUART2) */
#define RTE_CMSIS_Driver_USART23        /* Driver USART23 (LPUART3) */
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32f4xx.h"


#endif /* RTE_COMPONENTS_H */
